# -*- coding: utf-8 -*-
"""Student-Depression-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhTpt16HAB2bAWQCwCRqm5dMezJtGoZ2

# ## 1. Import Required Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from google.colab import files

"""# ## 2. Upload and Load Dataset

"""

print("Please upload your dataset CSV file.")
uploaded = files.upload()
dataset_path = next(iter(uploaded))
df = pd.read_csv(dataset_path)

print("\nInitial Data Shape:", df.shape)

"""# ## 3. Data Cleaning

"""

def clean_data(df):
    df = df.copy()
    df.drop_duplicates(inplace=True)
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
    categorical_cols = df.select_dtypes(include='object').columns
    for col in categorical_cols:
        df[col].fillna(df[col].mode()[0], inplace=True)
    return df

"""
# Execute Cleaning

"""

df = clean_data(df)
print("Data cleaning completed.")

"""# ## 4. Outlier Detection and Handling



"""

def detect_outliers_zscore(df, threshold=3):
    outlier_indices = []
    for col in df.select_dtypes(include=[np.number]).columns:
        z_scores = np.abs(stats.zscore(df[col]))
        outliers = np.where(z_scores > threshold)
        outlier_indices.extend(outliers[0])
    return list(set(outlier_indices))

"""# Detect and Handle Outliers"""

outliers = detect_outliers_zscore(df)
print(f"Number of outliers detected: {len(outliers)}")

def handle_outliers(df):
    df = df.copy()
    for col in df.select_dtypes(include=[np.number]).columns:
        lower = df[col].quantile(0.01)
        upper = df[col].quantile(0.99)
        df[col] = np.clip(df[col], lower, upper)
    return df

"""# Execute Outlier Handling

"""

df = handle_outliers(df)
print("Outlier handling completed.")

"""# ## 5. Feature Engineering"""

def feature_engineering(df):
    df = df.copy()
    if 'age' in df.columns:
        df['age_group'] = pd.cut(df['age'], bins=[0, 18, 22, 30, 100], labels=['Teen', 'Young Adult', 'Adult', 'Older'])
    if {'anxiety', 'stress'}.issubset(df.columns):
        df['mental_health_risk'] = df['anxiety'] + df['stress']
    return df

"""# Execute Feature Engineering

"""

df = feature_engineering(df)
print("Feature engineering completed.")

"""# ## 6. Encode Categorical Variables

"""

def encode_categoricals(df):
    df = df.copy()
    categorical_cols = df.select_dtypes(include=['object', 'category']).columns
    for col in categorical_cols:
        df[col] = df[col].astype('category').cat.codes
        df[col] = df[col].astype('int64')
    return df

"""# Execute Encoding"""

print("Before encoding:", df.dtypes)
df = encode_categoricals(df)
print("Encoding completed.")
print("After encoding:", df.dtypes)

"""# ## 7. Train-Test Split

"""

def split_data(df, target_col):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    return train_test_split(X, y, test_size=0.2, random_state=42)

"""# Define Target and Split

"""

target_column = 'depression'  # Update if needed
if target_column not in df.columns:
    raise ValueError(f"Target column '{target_column}' not found in dataset columns: {df.columns.tolist()}")

X_train, X_test, y_train, y_test = split_data(df, target_column)
print(f"Train shape: {X_train.shape}, Test shape: {X_test.shape}")

"""# ## 8. Correlation Analysis

"""

def correlation_analysis(df):
    numeric_df = df.select_dtypes(include=[np.number])
    corr_matrix = numeric_df.corr()
    plt.figure(figsize=(15, 12))
    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", square=True)
    plt.title('Correlation Matrix Heatmap')
    plt.show()

"""# Execute Correlation Analysis

"""

correlation_analysis(df)

"""# ## 9. Clustering Analysis (KMeans + PCA Visualization)

# PCA
"""

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_train)

"""# KMeans Clustering"""

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X_pca)
clusters = kmeans.labels_

"""# Plot Clusters"""

plt.figure(figsize=(8,6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=clusters, cmap='viridis', alpha=0.6)
plt.title('KMeans Clustering Visualization (PCA 2D)')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.grid(True)
plt.show()

"""# Elbow Method to Determine Optimal k"""

inertia = []
k_values = range(1, 10)
for k in k_values:
    km = KMeans(n_clusters=k, random_state=42)
    km.fit(X_pca)
    inertia.append(km.inertia_)

plt.figure(figsize=(8,6))
plt.plot(k_values, inertia, 'bo-')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method For Optimal k')
plt.grid(True)
plt.show()

print("Clustering analysis completed! ✅")

"""# ## 10. Baseline Model: Dummy Classifier"""

dummy_clf = DummyClassifier(strategy="most_frequent", random_state=42)
dummy_clf.fit(X_train, y_train)
y_pred_dummy = dummy_clf.predict(X_test)

print("\nBaseline Dummy Classifier Performance:")
print(classification_report(y_test, y_pred_dummy))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dummy))

"""# ## 11. Classification Models Training and Evaluation

"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "SVM": SVC(random_state=42)
}

"""# Utility function to evaluate models

"""

def evaluate_model(name, y_true, y_pred, results_list):
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    results_list.append({
        'Model': name,
        'Accuracy': acc,
        'Precision': prec,
        'Recall': rec,
        'F1-Score': f1
    })

"""# Train and evaluate all models"""

results = []
for name, model in models.items():
    print(f"\nTraining {name}...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred))
    evaluate_model(name, y_test, y_pred, results)

"""# Evaluate Dummy Classifier separately

"""

evaluate_model('Dummy Classifier', y_test, y_pred_dummy, results)

"""# ## 12. Final Model Evaluation Comparison

"""

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='F1-Score', ascending=False)

print("\nModel Evaluation Metrics Comparison:")
print(results_df)