# -*- coding: utf-8 -*-
"""T7 Feature Engineering and Transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpvQCrguoicCyyZ9Fky7uIyAFntEDgZO
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Student Depression Dataset.csv")
print(df.columns.tolist())

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Load the dataset
df = pd.read_csv("Student Depression Dataset.csv")

# Ensure 'Sleep Duration' is numeric
df['Sleep Duration'] = pd.to_numeric(df['Sleep Duration'], errors='coerce')

# 1. Age Group
def age_group(age):
    if age <= 19:
        return 'Teen'
    elif 20 <= age <= 25:
        return 'Young Adult'
    else:
        return 'Adult'

df['Age_Group'] = df['Age'].apply(age_group)

# 2. CGPA Category
df['CGPA_Category'] = pd.cut(df['CGPA'], bins=[0, 6, 8, 10], labels=['Low', 'Average', 'High'])

# 3. Sleep Quality from Sleep Duration (after converting to numeric)
df['Sleep_Quality'] = pd.cut(
    df['Sleep Duration'],
    bins=[0, 5, 7, 12],
    labels=['Poor Sleep', 'Average Sleep', 'Good Sleep']
)

# 4. Overall Stress Score (normalized)
stress_cols = ['Academic Pressure', 'Financial Stress', 'Work Pressure']
df['Overall_Stress'] = df[stress_cols].sum(axis=1)
df['Overall_Stress'] = MinMaxScaler().fit_transform(df[['Overall_Stress']])

# 5. Work-Study Load Index
df['Work_Study_Load'] = df['Work/Study Hours'] / (df['Sleep Duration'] + 1e-3)

# 6. Feature Interactions
df['Academic_x_Satisfaction'] = df['Academic Pressure'] * df['Study Satisfaction']
df['JobSat_x_WorkPressure'] = df['Job Satisfaction'] * df['Work Pressure']

# 7. One-hot Encoding
categorical_cols = ['Age_Group', 'CGPA_Category', 'Sleep_Quality', 'Gender', 'Degree']
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# 8. Normalize the Work_Study_Load
df_encoded['Work_Study_Load'] = MinMaxScaler().fit_transform(df_encoded[['Work_Study_Load']])

# 9. Save Engineered Dataset
df_encoded.to_csv("student_depression_engineered.csv", index=False)
print("✅ Feature engineering complete. File saved as student_depression_engineered.csv")

from google.colab import files
files.download("student_depression_engineered.csv")

