# -*- coding: utf-8 -*-
"""T7 Feature Engineering and Transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpvQCrguoicCyyZ9Fky7uIyAFntEDgZO
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Student Depression Dataset.csv")
print(df.columns.tolist())

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Load the dataset
df = pd.read_csv("Student Depression Dataset.csv")

# Ensure 'Sleep Duration' is numeric
df['Sleep Duration'] = pd.to_numeric(df['Sleep Duration'], errors='coerce')

# 1. Age Group
def age_group(age):
    if age <= 19:
        return 'Teen'
    elif 20 <= age <= 25:
        return 'Young Adult'
    else:
        return 'Adult'

df['Age_Group'] = df['Age'].apply(age_group)

# 2. CGPA Category
df['CGPA_Category'] = pd.cut(df['CGPA'], bins=[0, 6, 8, 10], labels=['Low', 'Average', 'High'])

# 3. Sleep Quality from Sleep Duration (after converting to numeric)
df['Sleep_Quality'] = pd.cut(
    df['Sleep Duration'],
    bins=[0, 5, 7, 12],
    labels=['Poor Sleep', 'Average Sleep', 'Good Sleep']
)

# 4. Overall Stress Score (normalized)
stress_cols = ['Academic Pressure', 'Financial Stress', 'Work Pressure']
df['Overall_Stress'] = df[stress_cols].sum(axis=1)
df['Overall_Stress'] = MinMaxScaler().fit_transform(df[['Overall_Stress']])

# 5. Work-Study Load Index
df['Work_Study_Load'] = df['Work/Study Hours'] / (df['Sleep Duration'] + 1e-3)

# 6. Feature Interactions
df['Academic_x_Satisfaction'] = df['Academic Pressure'] * df['Study Satisfaction']
df['JobSat_x_WorkPressure'] = df['Job Satisfaction'] * df['Work Pressure']

# 7. One-hot Encoding
categorical_cols = ['Age_Group', 'CGPA_Category', 'Sleep_Quality', 'Gender', 'Degree']
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# 8. Normalize the Work_Study_Load
df_encoded['Work_Study_Load'] = MinMaxScaler().fit_transform(df_encoded[['Work_Study_Load']])

# 9. Save Engineered Dataset
df_encoded.to_csv("student_depression_engineered.csv", index=False)
print("✅ Feature engineering complete. File saved as student_depression_engineered.csv")

from google.colab import files
files.download("student_depression_engineered.csv")

"""# T8 – Data Quality Verification

**Task Duration:** April 10 – April 11, 2025  
**Assigned To:** All  
**Dependencies:** T5 (Data Cleaning), T6 (Outlier Detection), T7 (Feature Engineering)  
**Deliverable:** Data Quality Verification Report

---

## Objective

To validate the consistency, completeness, and readiness of the processed dataset (`student_depression_engineered.csv`) for downstream analysis and modeling. This task ensures that no critical data issues remain after cleaning, transformation, and feature engineering.

---

## Key Checks Performed

### 1. **Missing Values Detection**
- Verified columns for presence of `NaN` values
- Special focus on:
  - `Sleep Duration`: Found fully missing (to be excluded from modeling)
  - `Work_Study_Load`: Derived from `Sleep Duration`, also fully missing
- Remaining columns are complete or have minimal missingness

---

### 2. **Data Types Verification**
- All numeric, categorical, and boolean features confirmed to be in correct formats
- One-hot encoded columns (`Age_Group`, `CGPA_Category`, `Degree`, etc.) are boolean
- Target variable (`Depression`) is correctly formatted as integer

---

### 3. **Duplicate Entries Check**
- No duplicate rows found in the dataset

---

### 4. **Outlier Confirmation**
- Outliers were already handled in T6
- Visual confirmation via boxplots (see T6 repository: `Outlier Analysis Report/plots/`)

---

### 5. **Sanity Checks on Engineered Features**
- `Overall_Stress`: Normalized and within [0, 1] range
- `Academic_x_Satisfaction` and `JobSat_x_WorkPressure`: No extreme or invalid values
- `Sleep_Quality`, `Work_Study_Load`: Not used in downstream modeling due to `Sleep Duration` being fully missing

---

##Outcome

- Dataset is **clean, consistent, and validated** (excluding two derived features due to missing base column)
- Ready for:
  - Descriptive statistics (T9)
  - Correlation analysis (T11)
  - Modeling pipeline (T13 onward)

**Verified File:** `student_depression_engineered.csv`  
**Note:** `Sleep Duration`, `Sleep_Quality`, and `Work_Study_Load` flagged for exclusion or future imputation.

---

## Next Steps

Proceed to:
- T9 – Descriptive Statistics and Distribution Analysis
- T10 – Demographic Analysis
- T11 – Correlation Analysis


"""